version: "3"

services:
  source_system:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: adventure_works
      MYSQL_PASSWORD: secret
    volumes:
      - ./source_system_init/AdventureWorks2019.sql:/docker-entrypoint-initdb.d/init.sql
